import 'package:flutter/material.dart';import 'package:ideabox_2/core/app_export.dart';import 'package:ideabox_2/widgets/app_bar/appbar_image.dart';import 'package:ideabox_2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:ideabox_2/widgets/app_bar/custom_app_bar.dart';import 'package:ideabox_2/widgets/custom_button.dart';import 'package:ideabox_2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class ForgotPasswordErrorStateScreen extends StatelessWidget {TextEditingController inputfielddigitalController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(top: false, bottom: false, child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(47.00), leadingWidth: 32, leading: AppbarImage(height: getSize(16.00), width: getSize(16.00), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 16, top: 16, bottom: 15), onTap: () => onTapArrowleft3(context)), title: AppbarSubtitle3(text: "Back", margin: getMargin(left: 4)), styleType: Style.bgFillGray100), body: Form(key: _formKey, child: Container(width: size.width, padding: getPadding(left: 16, top: 32, right: 16, bottom: 32), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgLayer1DeepPurpleA200, height: getVerticalSize(56.00), width: getHorizontalSize(141.00), alignment: Alignment.center), Padding(padding: getPadding(left: 7, top: 25), child: Text("Forgot Password?", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium24)), Container(width: getHorizontalSize(327.00), margin: getMargin(left: 7, top: 2), child: Text("Don’t worry, fill your email and we’ll send you a link to reset your password. ", maxLines: null, textAlign: TextAlign.left, style: AppStyle.txtRobotoRegular16Bluegray8009a)), Padding(padding: getPadding(top: 22), child: RichText(text: TextSpan(children: [TextSpan(text: "Email", style: TextStyle(color: ColorConstant.gray900, fontSize: getFontSize(16), fontFamily: 'Poppins', fontWeight: FontWeight.w600)), TextSpan(text: "*", style: TextStyle(color: ColorConstant.red500, fontSize: getFontSize(16), fontFamily: 'Poppins', fontWeight: FontWeight.w600))]), textAlign: TextAlign.left)), CustomTextFormField(width: 358, focusNode: FocusNode(), controller: inputfielddigitalController, hintText: "type your email", margin: getMargin(top: 1), variant: TextFormFieldVariant.OutlineGray400, shape: TextFormFieldShape.RoundedBorder8, fontStyle: TextFormFieldFontStyle.PoppinsRegular14, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress), Padding(padding: getPadding(top: 1), child: Text("Incorrect Email", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsRegular12Red500)), CustomButton(height: 52, width: 358, text: "Submit", margin: getMargin(top: 14, bottom: 5), variant: ButtonVariant.FillDeeppurpleA200, shape: ButtonShape.RoundedBorder8, padding: ButtonPadding.PaddingAll13, fontStyle: ButtonFontStyle.PoppinsBold16)]))))); } 
onTapArrowleft3(BuildContext context) { Navigator.pop(context); } 
 }
